title: "ğŸ“½ï¸ ÙØ§ØµÙ„ Ø£ÙÙ„Ø§Ù…"
baseurl: ""
url: "https://github.com/9z9z/cinebox"
description: "Ù…ÙˆÙ‚Ø¹ Ù„Ø¹Ø±Ø¶ Ø§Ù„Ø£ÙÙ„Ø§Ù… ÙˆØ§Ù„Ù…Ø³Ù„Ø³Ù„Ø§Øª ÙˆØ§Ù„Ø£Ù†Ù…ÙŠ"
author: "bbkb"
collections:
  movies:
    output: true
  series:
    output: true
  anime:
    output: true
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 6
paginate_path: "/page:num/"
